WebUI/electron/main.ts
**Description:** Can resize and use window snapping
**Related Issue:** none
Enabled the Following in Electron:
```
transparent: true,
resizable: false,
```
Tested all 4 corners for resizing.
Tried snapping the window in my environment. 
**Checklist:**
=> feature: resizable and snappable window

readme.md
[Coverity Scan enabled](https://scan.coverity.com/projects/ai-playground)
**Checklist:**
=> [Doc] Add Coverity badge

WebUI/build/scripts/fetch-python-package-resources.js, WebUI/build/scripts/install-full-python-env.js, WebUI/build/scripts/provide-electron-build-resources.js, WebUI/electron/subprocesses/aiBackendService.ts, WebUI/electron/subprocesses/apiService.ts, WebUI/electron/subprocesses/comfyUIBackendService.ts, WebUI/electron/subprocesses/osProcessHelper.ts
* use async `spawn` to prevent main process from blocking
* extract ls level zero logic to prevent unnecessary install operations
* remove ComfyUI from build scripts
Tested locally on BMG device
**Checklist:**
=> Improve responsiveness of Electron App

LlamaCPP/llama_adapter.py, LlamaCPP/llama_cpp_backend.py, WebUI/electron/subprocesses/apiService.ts
Llama.cpp backend did not load a new model after the first model was loaded.
* correctly load new model after model switch
Tested locally on BMG.
**Checklist:**
=> Fix llama cpp model switching

WebUI/external/workflows/Line2ImageHD-Fast.json, WebUI/external/workflows/Line2ImageHD-Quality.json
Add a second Line2Image workflow without LCM
* add new line2image workflow without LCM
Tested locally on BMG.
**Checklist:**
=> Add a second Line2Image workflow without LCM

WebUI/electron/subprocesses/comfyUIBackendService.ts, WebUI/external/workflows/FaceSwapHD.json, WebUI/external/workflows/fluxQ4.json, WebUI/src/assets/js/const.ts, WebUI/src/assets/js/store/backendServices.ts, WebUI/src/assets/js/store/comfyUi.ts, WebUI/src/assets/js/store/imageGeneration.ts, WebUI/src/assets/js/store/stableDiffusion.ts, WebUI/src/components/SettingsImageGeneration.vue, WebUI/src/env.d.ts, WebUI/src/views/Create.vue, service/aipg_utils.py, service/comfyui_downloader.py, service/model_downloader.py, service/service_config.py, service/web_api.py, service/web_request_bodies.py
Improve workflow mode custom node handling
* restart comfyui automatically after custom node install
* support additional workflow requirements to allow installation of reactore node for faceswap
* use git commit hashes to specify custom node and comfyui versions to keep workflows stable
* add non-commercial tag to face-swap workflow 
Tested locally on BMG
**Checklist:**
=> Improve workflow mode custom node handling

WebUI/src/assets/css/compontents.css, WebUI/src/assets/js/store/textInference.ts, WebUI/src/components/InstallationManagement.vue, WebUI/src/components/SettingsBasic.vue
Implement small UX improvements 
* add "Developer Log" button to basic settings
* add experimental tag to Llama.cpp backend
* small UI fixes
Tested locally on BMG
**Checklist:**
=> Implement small UX improvements 

WebUI/src/views/Answer.vue
Button for scrolling down to latest message. Will scroll to bottom auto when changing conversation.
- New button to scroll down to latest message/bottom of conversation. 
- Automatically scrolls to bottom when click between different conversations. 
- Scrolled up and clicked button for it to scroll the conversation down. 
- Clicked on different conversations.
- Adjusted window sizes to ensure coherency of button alignment.  
- Generated new messages to ensure that the button does not glitch.
**Screenshots:**
https://github.com/user-attachments/assets/1cbf3c92-50fd-44f1-95a4-581a8f6b6841
**Checklist:**
=> feature: button for scrolling down to latest message. Will scroll to bottom auto when changing conversation.

WebUI/package.json, WebUI/src/assets/js/store/globalSetup.ts
This PR makes some minor adjustments for the upcoming 2.0.4-beta release.
* increment version
* fix llama.cpp default model
Tested locally
**Checklist:**
=> Adjust default model and AIPG version

WebUI/build/scripts/fetch-python-package-resources.js
=> 修复BUG (fix typo)

LlamaCPP/llama_adapter.py, LlamaCPP/llama_params.py, WebUI/src/assets/js/markdownParser.ts, WebUI/src/assets/js/store/textInference.ts, WebUI/src/components/SettingsBasic.vue, WebUI/src/views/Answer.vue, service/llm_biz.py
Disables Enter key submissions during processing, renders questions as raw text with improved Markdown for code blocks, repositions key UI elements, displays the model name during processing, adds a performance metrics toggle for LlamaCpp, restricts max tokens adjustments to IPEX users, and cleans up "thinking" text from reasoning model outputs.
- Disabled Enter key submission while an answer is processing.
- Fixed questions to display as raw text and improved Markdown rendering for code blocks.
- Moved the sidebar toggle button above the conversation list and repositioned font size settings into the settings tab.
- Updated the interface to show the model name during processing.
- Introduced a toggle to display metrics, with specific support for …
=> Implement fixes, token adjuster, metrics with Llamacpp

service/requirements.txt
This PR fixes .md files in embedding upload
* bump version of `unstructured`
Test locally on B580
**Checklist:**
=> Fix .md files in embedding upload

WebUI/electron/subprocesses/comfyUIBackendService.ts, WebUI/src/assets/js/store/models.ts, WebUI/src/views/Answer.vue
This PR implements some smaller adjustments for an upcoming release.
* adjust OpenVINO models
* fix comfyui installation issue
* disable RAG toggle for OpenVINO
Tested locally on B580
**Checklist:**
=> Implement some adjustments for upcoming release

WebUI/src/assets/js/store/comfyUi.ts, service/comfyui_downloader.py, service/web_api.py, service/web_request_bodies.py
This PR improves the Workflow Mode installation logic for custom nodes by shutting down ComfyUI during custom ndoe installation to avoid issues with locked resources.
It also adds logic to hotfix custom nodes in case of upstream bugs in custom nodes.
* shut down ComfyUI backend during custom node installation
* patch reactor node after download to fix [nsfw detection bug](https://github.com/Gourieff/ComfyUI-ReActor/issues/62)
Tested locally on BMG
**Screenshots:**
If applicable, please provide screenshots or GIFs or videos to visually demonstrate the changes made.
**Checklist:**
=> Improve Workflow Mode installation logic

LlamaCPP/llama_adapter.py, LlamaCPP/llama_cpp_backend.py, WebUI/src/components/SettingsBasic.vue
This PR enables the max token setting for llama.cpp
* enable max_tokens setting for llama.cpp
Tested locally on B580
**Screenshots:**
**Checklist:**
=> Enable max token setting for llama.cpp

WebUI/build/build-config.json, WebUI/external/workflows/Video.json, WebUI/src/assets/js/store/models.ts, WebUI/src/components/ui/slider/ResolutionPicker.vue
Some small adjustments for the upcoming release
* add tinyllama to openvino model selection
* patch reactor node to fix nsfw detection
* change name and tags of video workflow to "Txt To Video (LTX Video) (high-vram)"
* add 3rdpartynoticeslicenses.txt to bundle
Tested locally on B580
**Checklist:**
=> Implement some more adjustments for upcoming release

WebUI/src/components/SettingsImageGeneration.vue, WebUI/src/views/Answer.vue
New UI for for Answer tab to include more settings options such as max token, and backend select and more. Increase image batch size. Fix starting timer for reasoning. 
* Change reasoning start time to after model loads
* Increase image batch size
* Backend dropdown and other Answer settings to main Answer tab view
Tested locally on A770
**Checklist:**
=> Updates and fixes to Answer Tab

WebUI/src/assets/js/store/stableDiffusion.ts
This PR fixes the NSFW placeholder image, which was broken since moving the image output to a different location.
* load nsfw placeholder as inline dataURL
Tested locally on B580
**Checklist:**
=> Fix NSFW placeholder image

WebUI/electron/subprocesses/updateIntelWorkflows.ts, WebUI/src/assets/js/store/models.ts
This PR adjusts the image workflow source to the `main` branch and adds an additional embedding model
Tested locally on B580.
**Checklist:**
=> Adjust workflow source and add embedding model

WebUI/src/views/Answer.vue
UI fix in Answer section. Collapsible tab for reasoning models fixed when changing models. 
* Before and after section for thinking now receives the model for that chat message. 
Tested locally on A770
**Checklist:**
=> Update to fix reasoning models text rendering issue with current model

backend-shared/utils.py
This PR fixes an issue where an incorrect hash algorithm was still in use 🤦 
Tested locally on B580.
**Checklist:**
=> Actually use sha256

WebUI/electron/subprocesses/service.ts, WebUI/external/backend-versions.json, WebUI/src/assets/js/store/textInference.ts
This PR updates the OpenVINO version to 2025.3.0
**Checklist:**
=> Upgrade OpenVINO to 2025.3.0
